# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

docker_img: &docker_img
  docker:
    - image: circleci/node:13.8.0

jobs:
  build:
    <<: *docker_img
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm-packages"
          paths: 
            - /src/node_modules
      - run: npm run lint

  test:
    <<: *docker_img
    steps: 
      - checkout
      - restore_cache:
          keys: "npm-packages"
      - run: npm i
      - run: npm run test
  
  analyze:
    <<: *docker_img
    steps:
      - checkout
      - restore_cache:
          keys: "npm-packages"
      - run: npm audit


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
